// Single source of truth for all routes.
// App.jsx maps <Route> entries from this list.
// scripts/prerender.js iterates this list to capture per-route HTML.
// scripts/generate-sitemap.js emits one <url> entry per route.
//
// To add a route: add an entry here AND add a {path: Component} pair to
// COMPONENTS in App.jsx. Removing a route here removes it from the sitemap
// and the prerender — even if a stray <Route> still exists in App.jsx.

export const ORIGIN = "https://ca-policy.com";

export const routes = [
  {
    path: "/",
    title: "California: A State of Crisis? — Policy Analysis Dashboards",
    description: "Interactive policy analysis of California's gasoline prices, electricity rates, housing, homelessness, water, high-speed rail, insurance, education, crime, infrastructure, CEQA, fast-food wages, road charges, healthcare wages, unions, immigration, gerrymandering, and more. Data-driven. Source-cited.",
    ogType: "website",
    sitemap: { changefreq: "weekly", priority: "1.0" },
    prerender: { marker: "Refinery closures, boutique fuel mandates" },
  },
  {
    path: "/gas",
    title: "California's Gasoline Crisis | CA Policy",
    heroTitle: "California's Gasoline Crisis",
    description: "Refinery closures, boutique fuel mandates, and geographic isolation created the most expensive fuel market in America.",
    ogType: "article",
    sitemap: { changefreq: "monthly", priority: "0.9" },
    prerender: { marker: "Gasoline Crisis" },
  },
  {
    path: "/elec",
    title: "California's Electricity Crisis | CA Policy",
    heroTitle: "California's Electricity Crisis",
    description: "Double the price, half the usage. Mandates, wildfires, and nuclear politics drive the priciest electricity on the mainland.",
    ogType: "article",
    sitemap: { changefreq: "monthly", priority: "0.9" },
    prerender: { marker: "Electricity Crisis" },
  },
  {
    path: "/water",
    title: "California's Water Crisis | CA Policy",
    heroTitle: "California's Water Crisis",
    description: "80% of water to agriculture, restrictions on residents, and proven solutions rejected.",
    ogType: "article",
    sitemap: { changefreq: "monthly", priority: "0.8" },
    prerender: { marker: "Water Crisis" },
  },
  {
    path: "/globe",
    title: "Supply Routes — 12,300 nm Journey of CA Gasoline | CA Policy",
    description: "Interactive 3D globe showing the absurd journey of California's gasoline imports.",
    ogType: "article",
    sitemap: { changefreq: "monthly", priority: "0.7" },
    prerender: { marker: "Global Supply Routes" },
  },
  {
    path: "/exodus",
    title: "The California Exodus | CA Policy",
    heroTitle: "The California Exodus",
    description: "1.7 million residents gone since 2020. Companies, tax revenue, and talent following them out.",
    ogType: "article",
    sitemap: { changefreq: "monthly", priority: "0.8" },
    prerender: { marker: "Exodus" },
  },
  {
    path: "/rail",
    title: "High-Speed Rail: $126B and Counting | CA Policy",
    heroTitle: "High-Speed Rail: $126B and Counting",
    description: "18 years. $18 billion spent. Zero passengers. The most expensive infrastructure failure in American history.",
    ogType: "article",
    sitemap: { changefreq: "monthly", priority: "0.8" },
    prerender: { marker: "High-Speed Rail" },
  },
  {
    path: "/housing",
    title: "Housing: The $905K Dream | CA Policy",
    heroTitle: "Housing: The $905K Dream",
    description: "82% of households priced out. 3 million unit shortage. 25 years to save for a down payment.",
    ogType: "article",
    sitemap: { changefreq: "monthly", priority: "0.9" },
    prerender: { marker: "$905K Dream" },
  },
  {
    path: "/homeless",
    title: "Homelessness: 183,000 and Counting | CA Policy",
    heroTitle: "Homelessness: 183,000 and Counting",
    description: "$24 billion spent. Numbers went up. 7 people die daily on LA County streets alone.",
    ogType: "article",
    sitemap: { changefreq: "monthly", priority: "0.8" },
    prerender: { marker: "183,000" },
  },
  {
    path: "/insurance",
    title: "Insurance: The Market That Broke | CA Policy",
    heroTitle: "Insurance: The Market That Broke",
    description: "7 of 12 top insurers leaving. $51.7B in fire damage. 30 years of suppressed pricing coming due.",
    ogType: "article",
    sitemap: { changefreq: "monthly", priority: "0.8" },
    prerender: { marker: "Market That Broke" },
  },
  {
    path: "/col",
    title: "Cost of Living: The California Tax | CA Policy",
    heroTitle: "Cost of Living: The California Tax",
    description: "The highest taxes, gas, groceries, and utilities in the continental U.S. — and it's accelerating.",
    ogType: "article",
    sitemap: { changefreq: "monthly", priority: "0.9" },
    prerender: { marker: "California Tax" },
  },
  {
    path: "/edu",
    title: "Education: Spending More, Getting Less | CA Policy",
    heroTitle: "Education: Spending More, Getting Less",
    description: "$128B budget. 46th in reading. 45th in math. The most expensive underperformance in the nation.",
    ogType: "article",
    sitemap: { changefreq: "monthly", priority: "0.8" },
    prerender: { marker: "Spending More, Getting Less" },
  },
  {
    path: "/biz",
    title: "Business Climate: The Regulation State | CA Policy",
    heroTitle: "Business Climate: The Regulation State",
    description: "395 new regulations per year. 18,000+ companies left since 2018. The state that taxes success and subsidizes failure.",
    ogType: "article",
    sitemap: { changefreq: "monthly", priority: "0.8" },
    prerender: { marker: "Regulation State" },
  },
  {
    path: "/crime",
    title: "Crime: The Accountability Crisis | CA Policy",
    heroTitle: "Crime: The Accountability Crisis",
    description: "Prop 47 raised the theft threshold. Smash-and-grabs tripled. DA recall movements in 5 counties.",
    ogType: "article",
    sitemap: { changefreq: "monthly", priority: "0.8" },
    prerender: { marker: "Accountability Crisis" },
  },
  {
    path: "/infra",
    title: "Infrastructure: Grade C- | CA Policy",
    heroTitle: "Infrastructure: Grade C-",
    description: "$216B funding gap. 30% of roads poor. 65% of bridges past design life. The 5th largest economy on a D+ foundation.",
    ogType: "article",
    sitemap: { changefreq: "monthly", priority: "0.8" },
    prerender: { marker: "Grade C-" },
  },
  {
    path: "/ceqa",
    title: "CEQA: The Law That Blocks Everything | CA Policy",
    heroTitle: "CEQA: The Law That Blocks Everything",
    description: "One 1970 law. 55 years unreformed. The hidden engine behind every crisis on this site.",
    ogType: "article",
    sitemap: { changefreq: "monthly", priority: "0.8" },
    prerender: { marker: "CEQA" },
  },
  {
    path: "/conclusion",
    title: "Conclusions: The Pattern & The Path Forward | CA Policy",
    heroTitle: "Conclusions: The Pattern & The Path Forward",
    description: "Crises across California's policy landscape share one pattern. What caused them, who benefits, and what would fix them.",
    ogType: "article",
    sitemap: { changefreq: "monthly", priority: "0.8" },
    prerender: { marker: "Path Forward" },
  },
  {
    path: "/politics",
    title: "Political Structure: Why Nothing Changes | CA Policy",
    heroTitle: "Political Structure: Why Nothing Changes",
    description: "One-party supermajority. Union-funded campaigns. Gerrymandered maps. And 13 years without accountability.",
    ogType: "article",
    sitemap: { changefreq: "monthly", priority: "0.8" },
    prerender: { marker: "Why Nothing Changes" },
  },
  {
    path: "/fraud",
    title: "Fraud, Waste & Abuse | CA Policy",
    heroTitle: "Fraud, Waste & Abuse",
    description: "$20B in EDD fraud. 280+ hospice licenses revoked. $146B in estimated Medi-Cal losses. The real numbers and the inflated ones.",
    ogType: "article",
    sitemap: { changefreq: "monthly", priority: "0.8" },
    prerender: { marker: "EDD fraud" },
  },
  {
    path: "/healthcare",
    title: "Healthcare Financing: How It Actually Works | CA Policy",
    heroTitle: "Healthcare Financing: How It Actually Works",
    description: "Medicare, Medi-Cal, employer insurance, Covered CA — how the patchwork pays for care and why the cross-subsidy is breaking.",
    ogType: "article",
    sitemap: { changefreq: "monthly", priority: "0.8" },
    prerender: { marker: "Medi-Cal" },
  },
  {
    path: "/immigration",
    title: "Immigration & Population | CA Policy",
    heroTitle: "Immigration & Population",
    description: "10.9M immigrants, 1.46M domestic out-migration, and a $17-22B fiscal question California has never formally studied.",
    ogType: "article",
    sitemap: { changefreq: "monthly", priority: "0.8" },
    prerender: { marker: "Immigration" },
  },
  {
    path: "/fastfood",
    title: "The $20 Fast-Food Wage (AB 1228) | CA Policy",
    description: "AB 1228 at two years. Six studies. Two opposing narratives. The defensible read on California's sectoral fast-food minimum wage.",
    ogType: "article",
    sitemap: { changefreq: "monthly", priority: "0.9" },
    prerender: { marker: "AB 1228" },
  },
  {
    path: "/roadcharge",
    title: "California Road Charge & Mileage Fee | CA Policy",
    description: "California's gas tax is dying. The mileage-fee replacement: what's actually proposed, and why most coverage is wrong.",
    ogType: "article",
    sitemap: { changefreq: "monthly", priority: "0.9" },
    prerender: { marker: "Road Charge" },
  },
  {
    path: "/healthcarewage",
    title: "SB 525 Healthcare Minimum Wage | CA Policy",
    description: "California's $25/hr healthcare minimum wage by tier. Four schedules with different timelines.",
    ogType: "article",
    sitemap: { changefreq: "monthly", priority: "0.9" },
    prerender: { marker: "SB 525" },
  },
  {
    path: "/stategov",
    title: "How California Actually Governs | CA Policy",
    description: "Supermajority rules, the proposition system, money in politics, and the legislative calendar.",
    ogType: "article",
    sitemap: { changefreq: "monthly", priority: "0.8" },
    prerender: { marker: "Supermajority Rules" },
  },
  {
    path: "/unions",
    title: "California Labor Unions & Political Power | CA Policy",
    description: "How California's 2-million-member labor movement shapes wage law and the legislative agenda.",
    ogType: "article",
    sitemap: { changefreq: "monthly", priority: "0.8" },
    prerender: { marker: "labor movement" },
  },
  {
    path: "/gerrymandering",
    title: "Gerrymandering 2026: Mid-Decade Redistricting | CA Policy",
    description: "The largest mid-decade redistricting cycle in 60 years. Texas, California Prop 50, and four other states.",
    ogType: "article",
    sitemap: { changefreq: "monthly", priority: "0.9" },
    prerender: { marker: "redistricting" },
  },
  {
    path: "/wildfires",
    title: "California Wildfires & Forestry | CA Policy",
    description: "PG&E liability, federal forest mismanagement, and the 2025 LA fires that reshaped the state.",
    ogType: "article",
    sitemap: { changefreq: "monthly", priority: "0.9" },
    prerender: { marker: "Camp Fire" },
  },
];

// Static informational pages (already prerendered as static HTML in public/).
// Listed here so the sitemap picks them up.
export const staticPages = [
  {
    path: "/about",
    sitemap: { changefreq: "yearly", priority: "0.5" },
  },
];

export function metaByPath(pathname) {
  const r = routes.find((x) => x.path === pathname);
  return r || routes[0];
}
